server.port: 8090
camunda.rest.baseurl: http://localhost:8080/engine-rest/
camunda.externalTask.asyncResponseTimeout: 1000
camunda.externalTask.lockDuration: 1000
camunda.externalTask.calculatorWorker.topicSubscription: calculator
camunda.externalTask.workerId: external_calculator_worker
